In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([12,15,13,14,15,16])
b = np.array([1,2,1,3,-1,0])
c = np.array([1000,1035,900,790,815,1024])

In [8]:
data = np.array([a,b,c]).T
data

array([[  12,    1, 1000],
       [  15,    2, 1035],
       [  13,    1,  900],
       [  14,    3,  790],
       [  15,   -1,  815],
       [  16,    0, 1024]])

In [3]:
a,b,c

(array([12, 15, 13, 14, 15, 16]),
 array([ 1,  2,  1,  3, -1,  0]),
 array([1000, 1035,  900,  790,  815, 1024]))

In [4]:
mean_a = np.mean(a)
mean_b = np.mean(b)
mean_c = np.mean(c)

In [5]:
std_a = np.std(a)
std_b = np.std(b)
std_c = np.std(c)

In [9]:
score_a = (a-mean_a)/std_a
score_b = (b-mean_b)/std_b
score_c = (c-mean_c)/std_c

In [ ]:
score_a

In [ ]:
score_b

In [ ]:
score_c

In [11]:
np.array([score_a, score_b, score_c]).T

array([[-1.61245155,  0.        ,  0.73628063],
       [ 0.62017367,  0.77459667,  1.09091121],
       [-0.86824314,  0.        , -0.27694959],
       [-0.12403473,  1.54919334, -1.39150284],
       [ 0.62017367, -1.54919334, -1.13819529],
       [ 1.36438208, -0.77459667,  0.97945588]])

In [12]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()
X = scaler.fit_transform(data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [15]:
X

array([[-1.61245155,  0.        ,  0.73628063],
       [ 0.62017367,  0.77459667,  1.09091121],
       [-0.86824314,  0.        , -0.27694959],
       [-0.12403473,  1.54919334, -1.39150284],
       [ 0.62017367, -1.54919334, -1.13819529],
       [ 1.36438208, -0.77459667,  0.97945588]])